version: '3'

services:
  api:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: conda run --no-capture-output -n simpletrade python -m uvicorn simpletrade.api.server:app --host 0.0.0.0 --port 8002 --reload

  # 前端服务暂时注释掉，专注于后端开发
  # frontend:
  #   image: node:14
  #   working_dir: /app
  #   volumes:
  #     - ./web-frontend:/app
  #   ports:
  #     - "8080:8080"
  #   command: bash -c "npm install && npm run serve"
  #   depends_on:
  #     - api
